version: 2
updates:
- package-ecosystem: "pip"
  directory: "/scripts"
  schedule:
    interval: "weekly"
  versioning-strategy: increase-if-necessary
  prefix: chore(ci)
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  prefix: chore(ci)
