version: 2
updates:
- package-ecosystem: "pip"
  directory: "/scripts"
  schedule:
    interval: "weekly"
  versioning-strategy: increase-if-necessary
  commit-message:
    prefix: "chore(ci)"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "chore(ci)"
